-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:24:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Категории` (
  `idКатегории` INT NOT NULL,
  `название` VARCHAR(100) NULL,
  `Родительская категория` VARCHAR(45) NULL,
  PRIMARY KEY (`idКатегории`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары` (
  `id_товара` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `остаток` INT NOT NULL DEFAULT 0,
  `описание` TEXT(250) NULL,
  PRIMARY KEY (`id_товара`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Товары_категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары_категории` (
  `id_Товара` INT NOT NULL,
  `id_Категории` INT NULL,
  PRIMARY KEY (`id_Товара`, `id_Категории`),
  INDEX `категории_idx` (`id_Категории` ASC) VISIBLE,
  CONSTRAINT `id_товара INT FK`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Товары` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `категории`
    FOREIGN KEY (`id_Категории`)
    REFERENCES `mydb`.`Категории` (`idКатегории`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупатели` (
  `id_Покупателя` INT NOT NULL AUTO_INCREMENT,
  `логин` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `телефон` VARCHAR(20) NULL,
  `адрес` VARCHAR(200) NULL,
  PRIMARY KEY (`id_Покупателя`),
  UNIQUE INDEX `логин_UNIQUE` (`логин` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Заказы` (
  `id_Заказы` INT NULL AUTO_INCREMENT,
  `дата` DATETIME(25) NOT NULL,
  `статус` VARCHAR(20) NULL,
  `сумма` DECIMAL(12,2) NULL,
  `id_покупателя` INT NULL,
  PRIMARY KEY (`id_Заказы`),
  CONSTRAINT `покупатели`
    FOREIGN KEY (`id_Заказы`)
    REFERENCES `mydb`.`Покупатели` (`id_Покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Состав_заказа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Состав_заказа` (
  `id_заказа` INT NULL AUTO_INCREMENT,
  `id_товара` INT NULL,
  `Количество` INT NOT NULL,
  `цена_на_момент` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_заказа`),
  INDEX `товары_idx` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `заказы`
    FOREIGN KEY (`id_заказа`)
    REFERENCES `mydb`.`Заказы` (`id_Заказы`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Отзывы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Отзывы` (
  `id_отзыва` INT NULL AUTO_INCREMENT,
  `текст` TEXT(100) NULL,
  `оценка` INT NULL,
  `дата` DATE NULL,
  `id_товара` INT NULL,
  `id_покупателя` INT NULL,
  PRIMARY KEY (`id_отзыва`),
  CONSTRAINT `товары`
    FOREIGN KEY (`id_отзыва`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `покупатели`
    FOREIGN KEY (`id_отзыва`)
    REFERENCES `mydb`.`Покупатели` (`id_Покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
