-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:09:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Категории` (
  `idКатегории` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NULL,
  `Родительская категория` VARCHAR(45) NULL,
  PRIMARY KEY (`idКатегории`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары` (
  `id_товара` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `остаток` INT NOT NULL DEFAULT 0,
  `описание` TEXT NULL,
  PRIMARY KEY (`id_товара`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Товары_категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары_категории` (
  `id_Товара` INT NOT NULL,
  `id_Категории` INT NOT NULL,  -- Исправлено: NOT NULL (было NULL)
  PRIMARY KEY (`id_Товара`, `id_Категории`),
  INDEX `категории_idx` (`id_Категории` ASC) VISIBLE,
  CONSTRAINT `fk_товары_категории_товары`
    FOREIGN KEY (`id_Товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_товары_категории_категории`
    FOREIGN KEY (`id_Категории`)
    REFERENCES `mydb`.`Категории` (`idКатегории`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупатели` (
  `id_Покупателя` INT NOT NULL AUTO_INCREMENT,
  `логин` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `телефон` VARCHAR(20) NULL,
  `адрес` VARCHAR(200) NULL,
  PRIMARY KEY (`id_Покупателя`),
  UNIQUE INDEX `логин_UNIQUE` (`логин` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Заказы` (
  `id_Заказы` INT NOT NULL AUTO_INCREMENT,  -- Исправлено: NOT NULL (было NULL)
  `дата` DATETIME NOT NULL,  -- Исправлено: убран (25) - максимальная точность 6
  `статус` VARCHAR(20) NULL,
  `сумма` DECIMAL(12,2) NULL,
  `id_покупателя` INT NOT NULL,  -- Исправлено: NOT NULL для целостности
  PRIMARY KEY (`id_Заказы`),
  INDEX `idx_покупатели` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `fk_заказы_покупатели`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_Покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Состав_заказа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Состав_заказа` (
  `id_состава` INT NOT NULL AUTO_INCREMENT,  -- Добавлен суррогатный ключ
  `id_заказа` INT NOT NULL,  -- Исправлено: NOT NULL, убран AUTO_INCREMENT
  `id_товара` INT NOT NULL,  -- Исправлено: NOT NULL
  `Количество` INT NOT NULL,
  `цена_на_момент` DECIMAL(10,2) NOT NULL,  -- Лучше сделать NOT NULL
  PRIMARY KEY (`id_состава`),
  UNIQUE KEY `uk_заказ_товар` (`id_заказа`, `id_товара`),  -- Уникальность пары
  INDEX `товары_idx` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `fk_состав_заказа_заказы`
    FOREIGN KEY (`id_заказа`)
    REFERENCES `mydb`.`Заказы` (`id_Заказы`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_состав_заказа_товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Отзывы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Отзывы` (
  `id_отзыва` INT NOT NULL AUTO_INCREMENT,  -- Исправлено: NOT NULL (было NULL)
  `текст` TEXT NULL,  -- Исправлено: убран (100) - TEXT не имеет длины в скобках
  `оценка` INT CHECK (оценка BETWEEN 1 AND 5) NULL,
  `дата` DATE NULL,
  `id_товара` INT NOT NULL,  -- Исправлено: NOT NULL
  `id_покупателя` INT NOT NULL,  -- Исправлено: NOT NULL
  PRIMARY KEY (`id_отзыва`),
  INDEX `idx_товары` (`id_товара` ASC) VISIBLE,
  INDEX `idx_покупатели` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `fk_отзывы_товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_отзывы_покупатели`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_Покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;